-- AlterTable
ALTER TABLE "QRCode" ADD COLUMN "backgroundColor" TEXT DEFAULT '#FFFFFF';
ALTER TABLE "QRCode" ADD COLUMN "callToAction" TEXT DEFAULT 'Scan to Shop';
ALTER TABLE "QRCode" ADD COLUMN "cornerRadius" INTEGER DEFAULT 0;
ALTER TABLE "QRCode" ADD COLUMN "dotStyle" TEXT DEFAULT 'square';
ALTER TABLE "QRCode" ADD COLUMN "eyeStyle" TEXT DEFAULT 'square';
ALTER TABLE "QRCode" ADD COLUMN "foregroundColor" TEXT DEFAULT '#000000';
ALTER TABLE "QRCode" ADD COLUMN "frameStyle" TEXT DEFAULT 'square';
ALTER TABLE "QRCode" ADD COLUMN "gradientColor1" TEXT;
ALTER TABLE "QRCode" ADD COLUMN "gradientColor2" TEXT;
ALTER TABLE "QRCode" ADD COLUMN "gradientType" TEXT;
ALTER TABLE "QRCode" ADD COLUMN "logoUrl" TEXT;
